/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bphc.taxidriver.ui;

import bphc.taxidriver.Main;
import bphc.taxidriver.models.Booking;
import bphc.taxidriver.models.Location;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhijeet
 */
public class CurrentBooking extends javax.swing.JPanel {

    private Booking currentBooking;
    
    /**
     * Creates new form CurrentBooking
     */
    public CurrentBooking() {
        initComponents();
        
        String[] model = Arrays.stream(Location.values()).map(s -> s.toString()).toArray(String[]::new);
        cmbPickup.setModel(new DefaultComboBoxModel<>(model));
        cmbDropOff.setModel(new DefaultComboBoxModel<>(model));        
    }
    
    public void setBooking(Booking booking) {
        currentBooking = booking; 
        
        cmbPickup.setSelectedItem(booking.getPickupLocation().toString());
        cmbDropOff.setSelectedItem(booking.getDropOffLocation().toString());
        txtDriverName.setText(booking.getDriver().getFirstName() + " " + booking.getDriver().getLastName()); 
        txtPhNumber.setText(booking.getDriver().getPhNumber());
        txtDriverRating.setText(Integer.toString(booking.getDriver().getRating()));
   }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPickup = new javax.swing.JComboBox<>();
        cmbDropOff = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDriverName = new javax.swing.JTextField();
        btnArrived = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPhNumber = new javax.swing.JTextField();
        txtDriverRating = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CURRENT TAXI BOOKING");

        jLabel6.setText("Pick Up Location: ");

        cmbPickup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPickup.setDoubleBuffered(true);
        cmbPickup.setEnabled(false);

        cmbDropOff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDropOff.setDoubleBuffered(true);
        cmbDropOff.setEnabled(false);

        jLabel7.setText("Drop off Location: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cost of booking: ₹100");

        jLabel9.setText("Driver Name:");

        txtDriverName.setEnabled(false);

        btnArrived.setText("Mark As Arrived");
        btnArrived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrivedActionPerformed(evt);
            }
        });

        jLabel10.setText("Ph Number:");

        txtPhNumber.setEnabled(false);

        txtDriverRating.setEnabled(false);

        jLabel11.setText("Driver Rating:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPickup, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDriverRating, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbDropOff, 0, 157, Short.MAX_VALUE)
                                        .addComponent(txtDriverName))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnArrived)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDropOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDriverRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnArrived)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrivedActionPerformed
        currentBooking.setArrived(true);
        currentBooking.getDriver().setCurrentLocation(currentBooking.getDropOffLocation());
        currentBooking.getDriver().setBooked(false);
        
        // Ask customer for rating
        String val = JOptionPane.showInputDialog(null, "How would you rate this ride? (0-10) ");
        try {
            int rating = Integer.parseInt(val);
            currentBooking.getDriver().rate(rating);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error while parsing input. Make sure you've entered a valid number.");
            return;
        }
        
        if(currentBooking.save() && currentBooking.getDriver().save()) {
            Main.mainFrame.showCard("makeBooking"); // Let them make new booking now
        } else {
            JOptionPane.showMessageDialog(Main.mainFrame, "Failed to mark as arrived. Please try again.", "ERROR", 
                                          JOptionPane.ERROR);
        }
    }//GEN-LAST:event_btnArrivedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrived;
    private javax.swing.JComboBox<String> cmbDropOff;
    private javax.swing.JComboBox<String> cmbPickup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDriverName;
    private javax.swing.JTextField txtDriverRating;
    private javax.swing.JTextField txtPhNumber;
    // End of variables declaration//GEN-END:variables
}
